using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using static System.Net.Mime.MediaTypeNames;

public class PopUpTextSignScript : MonoBehaviour
{

    Canvas canvas;

    Camera mainCamera;

    private void Start()
    {
        canvas = GetComponentInChildren<Canvas>();

        mainCamera = GameObject.Find("Main Camera").GetComponent<Camera>();

        canvas.worldCamera = mainCamera;
    
        canvas.gameObject.SetActive(false);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            canvas.gameObject.SetActive(true);
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            canvas.gameObject.SetActive(false);
        }
    }
}
